name: HQS CI tests for rust pyo3 repos

on:
  workflow_dispatch:
  pull_request:
    branches: [$default-branch]

jobs:
  linting:
    uses: HQSquantumsimulations/.github/workflows/reusable_linting_rust_pyo3.yml@main

  unittests:
    uses: HQSquantumsimulations/.github/workflows/reusable_unittests_rust_pyo3.yml@main
    with:
      # Run tests also on windows runners
      windows: false
      # Run tests also on macos runners
      macos: true
      rust_package_name: "NAME_OF_RUST_PACKAGE_WITHOUT_PYTHON_INTERFACE"

  build_tests:
    uses: HQSquantumsimulations/.github/workflows/reusable_build_tests_rust_pyo3.yml@main
    with: 
      # Run tests also on windows runners
      windows: false
      # Run tests also on macos runners
      macos: true
      py_interface_folder: "NAME_OF_RUST_PACKAGE_WITH_PYTHON_INTERFACE"
      has_python_tests: true
